### ISSUE TITLE
Unable to install the Keto Helm Chart

### ISSUE THREAD

**Issue by deshetti** [ory/k8s#215]
**Describe the bug**

I followed the steps in the README to install Keto through the helm chart and running into the following error:

`Error: failed to download "ory/keto" (hint: running `helm repo update` may help)`

The command I am using is the one mentioned in README:

`helm install keto -n ory --set 'keto.config.dsn=memory' ory/keto`

**To Reproduce**

As mentioned above.

**Environment**

- Helm: v3
- Keto chart version: 0.1.0

**Additional context**

N/A

**Comment by aeneasr** [comment]
Hi there! I published a new version which includes a fix to the CI pipeline. So this should work next time you try it!

**Comment by jendrikjoe** [comment]
@aeneasr I am still seeing this issue 😉 
Reproducible example: 
```
helm repo update
helm search repo "ory/"
```

yields the following for me:
```
NAME                          	CHART VERSION	APP VERSION         	DESCRIPTION
ory/example-idp               	0.5.2        	1.4.6               	A Helm chart for deploying the reference implem...
ory/hive                      	0.1.0        	1.0                 	A ORY Hive Helm chart for Kubernetes
ory/hive-selfservice-ui-node  	0.1.0        	v0.0.1              	A Helm chart for ORY Hive's example ui for Kube...
ory/hydra                     	0.5.2        	v1.8.5              	A Helm chart for deploying ORY Hydra in Kubernetes
ory/hydra-maester             	0.5.2        	v0.0.19             	A Helm chart for Kubernetes
ory/kratos                    	0.5.2        	0.5.2-alpha.1-sqlite	A ORY Kratos Helm chart for Kubernetes
ory/kratos-selfservice-ui-node	0.5.2        	v0.1.1-alpha.1      	A Helm chart for ORY Kratos's example ui for Ku...
ory/maester                   	0.0.17       	v0.0.1              	A Helm chart for deployoing ORY Oathkeeper Rule...
ory/oathkeeper                	0.5.2        	v0.38.4-beta.1      	A Helm chart for deploying ORY Oathkeeper in Ku...
ory/oathkeeper-maester        	0.5.2        	v0.1.0              	A Helm chart for deploying ORY Oathkeeper Rule ...
```

**Comment by aeneasr** [comment]
Looks like the wrong files were updated :D

**Comment by jendrikjoe** [comment]
Thanks for fixing it so quickly 👍
